version: '3'

volumes:
  sqlitedatafiles:
  
networks: 
    pokedex-rede:
        driver: bridge
  
services:
      
  pokedex.net.api:
    container_name: pokedex.net.api  
    image: ${DOCKER_REGISTRY-}pokedex.netapi
    build:
      context: .
      dockerfile: src/Backend.Net/Backend.Api/Dockerfile
    restart: always      
    ports: 
      - "5000:80"
      - "5001:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pokedex-rede