// <auto-generated />
using System;
using Backend.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Infra.Migrations
{
    [DbContext(typeof(PokedexContext))]
    partial class PokedexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Backend.Domain.Models.MestrePokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("mestre_pokemon", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Models.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MestrePokemonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MestrePokemonId");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("Backend.Domain.Models.Pokemon", b =>
                {
                    b.HasOne("Backend.Domain.Models.MestrePokemon", "MestrePokemon")
                        .WithMany("Pokemons")
                        .HasForeignKey("MestrePokemonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("MestrePokemon");
                });

            modelBuilder.Entity("Backend.Domain.Models.MestrePokemon", b =>
                {
                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
